apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-node-app
  template:
    metadata:
      labels:
        app: devops-node-app
    spec:
      containers:
      - name: devops-node-app
        image: rogerprawin/devops-node-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
