apiVersion: v1
kind: Service
metadata:
  name: devops-node-app-service
spec:
  type: NodePort
  selector:
    app: devops-node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
